name: Angular Chess Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch to angular project
        run: cd angular-chess/

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"

      - name: Install dependencies
        run: |
          cd angular-chess/
          npm ci
      - name: Build
        run: |
          cd angular-chess/
          npm run build:ci
      - name: Test
        run: |
          cd angular-chess/
          npm run test:ci
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./angular-chess/dist/angular-chess/
